### PR TITLE
Added 3D SkySat data

### PR DESCRIPTION
**Pull request by m-mohr**
Ready for review @cholmes @tschaub 

Rendered version: https://radiantearth.github.io/stac-browser/#/external/raw.githubusercontent.com/m-mohr/open-stac/3d-skysat/stac/open-skysat-data/collection.json

You may want to copy the thumbnails to the Google bucket so that we can remove them from GitHub.

### CODE REVIEW

**Comment by cholmes** [comment]
Darn, I should have merged this one first, as it's the one I wanted in more. I don't have time to do the conflicts right now - could you handle them @m-mohr? 

I do want to add some better descriptions, so if I get to that soon maybe I'll just do it on this branch.

**Comment by m-mohr** [comment]
Yes, I'll go through the conflicts now. :-)

**Comment by m-mohr** [comment]
@cholmes Ready for re-review

**Review by cholmes — APPROVED** [review]
Looks great - thanks!

**Pull request merged**
